[setting]
# 邮箱地址列表文件
email_list = "emails.txt"
# 邮件主题
subject = "This is the subject"
# 邮件内容文件
email_content = "email.html"
# 发信速度（每分钟N封），设为0表示不延迟
limit = 0
# 代理设置，格式为http://ip:port，留空表示不使用代理
proxy = ""

[smtp]
server = ""  # SMTP 服务器地址
port = 465  # SMTP 服务器端口，SSL 通常为 465 或 587
username = ""  # SMTP 登录用户名，通常是发送邮箱地址
password = ""  # SMTP 登录密码
from_email = ""  # 发件邮箱